### ISSUE TITLE
Bug: Aimbot stops working

### ISSUE THREAD

**Issue by kazukeno** [Teklad/csgo-horker#19] opened 2018-08-14 07:27 UTC
I use the default aimbot settings and it stops working after some time and if you reinject the cheat in the same game then aimbot still wont work (wallhack will) but if you rejoin the server then it will work or if you join another server.

**Comment by w3bn00b** [comment] 2018-08-14 08:09
Inject(X) Execute(O)
this cheat is external

**Comment by d1monch1k** [comment] 2018-08-14 10:55
It becouse enemy have anti aim cheat

**Comment by mrtuxblux** [comment] 2018-08-14 11:52
Nope. Its not because i cant shoot anyone in casual lol

**Comment by mrtuxblux** [comment] 2018-08-14 11:52
They are not spinning either. And when i was on hvh i could actually headshot spinbotter.

**Comment by mrtuxblux** [comment] 2018-08-14 11:52
So it wont stop shooting spinners

**Comment by d1monch1k** [comment] 2018-08-14 12:04
Same problem....

**Comment by Teklad** [comment] 2018-08-14 19:59
Sounds to me like the entity list is getting screwed up.  I won't be able to really look at it until this weekend though.

**Comment by Teklad** [comment] 2018-08-15 01:29
So it occurred to me what might be happening.... Try setting UseMouseEvents to 1 in config when it happens again.... if it starts working again after that I'll be certain of what the issue is.

**Comment by Teklad** [comment] 2018-08-25 02:16
Did some updates finally... give it a go when you get a chance and let me know if you get any error output.... ANY error output.

I've made the aimbot verbose about errors for now until this can be resolved.  Also changed the way the entity list gets accessed so "hopefully" the issue might be resolved without any further intervention.

**Closed** 2018-08-26 15:29 UTC
Labels: bug
