### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by aa6my** [Teklad/csgo-horker#1] opened 2018-07-30 09:49 UTC
Its stuck in here

sudo ./src/horker
Attaching interrupt signal handler...Done.
Waiting for process...Done.
Waiting for client library...

**Comment by Teklad** [comment] 2018-07-30 09:54
It currently only supports panorama.  Did you set '-panorama' in your CSGO launch options?

**Comment by Teklad** [comment] 2018-07-30 12:17
I made a few changes to increase error output a bit.  Would you care to update and run it again when you get a chance and see if you get any new output?

I was throwing exceptions for non-fatal errors which was causing the hack to exit prematurely.

**Comment by d1monch1k** [comment] 2018-07-30 13:04
panorama is so lagging. i dont use it

**Comment by Teklad** [comment] 2018-07-30 13:18
I'll be getting the cheat working with non-panorama soon.  Flash is easy to implement so it will be added quickly.

Right now working on getting a config file set up so you can modify glow colors, etc.  Then I'll work on aim/trigger stuff.

**Comment by w3bn00b** [comment] 2018-07-30 13:19
@d1monch1k if you wanna cheat rn just code yourself
developer is not your mother, they just develop for fun(actually, who tf make open source hack without fun?)

**Comment by Teklad** [comment] 2018-07-30 13:21
@w3bn00b I don't actually cheat myself anymore.  I just enjoy the process of reverse engineering software.  This is is like a daily brain exercise for me.

**Comment by d1monch1k** [comment] 2018-07-30 13:22
@w3bn00b , I do not ask or force the developer to do anything, but only express my opinion. Your comment does not seem to be competent at least

**Comment by Teklad** [comment] 2018-07-30 13:34
@d1monch1k There you go.  It should be working with the normal client now.

**Comment by d1monch1k** [comment] 2018-07-30 13:40
@Teklad will test it soon

**Comment by ericek111** [comment] 2018-07-30 14:01
Feel free to use my sigs:
https://github.com/ericek111/linux-csgo-external-1/blob/master/main.cpp
https://github.com/ericek111/java-csgo-externals/blob/wip/src/me/lixko/csgoexternals/offsets/Offsets.java

**Comment by Teklad** [comment] 2018-07-30 14:05
Oh nice you have the EntityList signature.  That'll be extremely handy.

Cheers for this.

**Comment by d1monch1k** [comment] 2018-07-31 17:17
It's bad that cheat needs to be rebooted after every mm game

**Comment by Teklad** [comment] 2018-07-31 22:55
Works fine between multiple games on my end

**Comment by w3bn00b** [comment] 2018-08-01 05:05
@Teklad config added, check it out

**Comment by w3bn00b** [comment] 2018-08-03 02:43
why dont you close the issue?
the problem is solved now

**Closed** 2018-08-05 09:39 UTC
